---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, message=FALSE, error=FALSE, warning = FALSE,
  comment = "#>"
)
```

# luciano-maria-dr

## Organizandos os dados, compilando, selecionando e criando datas

```{r}
`%>%` <- magrittr::`%>%`

amazon_data <- rbind(readr::read_rds("data/df_1.rds"),
readr::read_rds("data/df_2.rds"),
readr::read_rds("data/df_3.rds")) %>%
  janitor::clean_names() %>%
  dplyr::mutate(year = as.numeric(substr(ymd, 1, 4)),
         month = as.numeric(substr(ymd, 5, 6)),
         day = as.numeric(substr(ymd, 7, 8)),
         date = lubridate::make_date(year,month,day)) %>%
  dplyr::select(-ymd, -flag_am) %>%
  dplyr::relocate(long,lat,date,year,month,day)
dplyr::glimpse(amazon_data)
```

## Mapas para teste

```{r}
amazon_data %>% dplyr::filter(month %in% c(4,7)) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(co2_mean = mean(co2,na.rm=TRUE),
                   n=dplyr::n(),
                   co2_stderr = sd(co2,na.rm=TRUE)/(n)^.5) %>% 
  dplyr::mutate(ym = lubridate::make_date(year,month,day=1)
                ) %>% 
  ggplot2::ggplot(ggplot2::aes(ym,co2_mean)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~month)+
  ggplot2::geom_smooth(method = "lm",se=FALSE)+
  ggpubr::stat_regline_equation(ggplot2::aes(
  label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~")))
```


```{r}
lm(co2_mean~year, data = amazon_data %>% dplyr::filter(month==4) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(co2_mean = mean(co2,na.rm=TRUE))
) %>% summary.lm()
```


```{r}
lm(co2_mean~year, data = amazon_data %>% dplyr::filter(month==7) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(co2_mean = mean(co2,na.rm=TRUE))
) %>% summary.lm()
```
```{r}
amazon_data %>% dplyr::filter(month %in% c(7,4)) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(co_mean = mean(co,na.rm=TRUE),
                   n=dplyr::n(),
                   co_stderr = sd(co,na.rm=TRUE)/(n)^.5) %>% 
  dplyr::mutate(ym = lubridate::make_date(year,month,day=1)
                ) %>% 
  ggplot2::ggplot(ggplot2::aes(ym,co_mean)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::facet_wrap(~month)+
  ggplot2::geom_smooth(method = "lm",se=FALSE) +
  ggpubr::stat_regline_equation(ggplot2::aes(
  label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~")))
```


```{r}
lm(co_mean~year, data = amazon_data %>% dplyr::filter(month==4) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(co_mean = mean(co,na.rm=TRUE))
) %>% summary.lm()
```

```{r}
lm(co_mean~year, data = amazon_data %>% dplyr::filter(month==7) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(co_mean = mean(co,na.rm=TRUE))
) %>% summary.lm()
```

```{r}
amazon_data %>% dplyr::filter(month %in% c(4,7)) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(ch4_mean = mean(ch4,na.rm=TRUE),
                   n=dplyr::n(),
                   ch4_stderr = sd(ch4,na.rm=TRUE)/(n)^.5) %>% 
  dplyr::mutate(ym = lubridate::make_date(year,month,day=1)
                ) %>% 
  ggplot2::ggplot(ggplot2::aes(ym,ch4_mean)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::geom_smooth(method = "lm",se=FALSE)+
  ggplot2::facet_wrap(~month)+
  ggpubr::stat_regline_equation(ggplot2::aes(
  label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~")))
```


```{r}
lm(ch4_mean~year, data = amazon_data %>% dplyr::filter(month==4) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(ch4_mean = mean(ch4,na.rm=TRUE))
) %>% summary.lm()
```

```{r}
lm(ch4_mean~year, data = amazon_data %>% dplyr::filter(month==7) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(ch4_mean = mean(ch4,na.rm=TRUE))
) %>% summary.lm()
```

```{r}
amazon_data %>% dplyr::filter(month %in% c(4,7)) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(frp_mean = mean(frp_mean,na.rm=TRUE),
                   n=dplyr::n(),
                   ch4_stderr = sd(frp_mean,na.rm=TRUE)/(n)^.5) %>% 
  dplyr::mutate(ym = lubridate::make_date(year,month,day=1)
                ) %>% 
  ggplot2::ggplot(ggplot2::aes(ym,frp_mean)) +
  ggplot2::geom_point() +
  ggplot2::geom_line() +
  ggplot2::geom_smooth(method = "lm",se=FALSE)+
  ggplot2::facet_wrap(~month)+
  ggpubr::stat_regline_equation(ggplot2::aes(
  label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~")))
```


```{r}
lm(frp_mean~year, data = amazon_data %>% dplyr::filter(month==4) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(frp_mean = mean(frp_mean,na.rm=TRUE))
) %>% summary.lm()
```

```{r}
lm(frp_mean~year, data = amazon_data %>% dplyr::filter(month==7) %>% 
  dplyr::group_by(year,month) %>% 
  dplyr::summarise(frp_mean = mean(frp_mean,na.rm=TRUE))
) %>% summary.lm()
```
## Espacializando

```{r}
amazon_data %>%
  dplyr::filter(month == 4) %>% 
  dplyr::group_by(year, long,lat) %>% 
  dplyr::summarise(co2_mean = mean(co2,na.rm=TRUE),
                   n=dplyr::n(),
                   co2_stderr = sd(co2,na.rm=TRUE)/(n)^.5) %>% 
  ggplot2::ggplot(ggplot2::aes(long,lat,color=co2_mean)) +
  ggplot2::geom_point() +
  ggplot2::facet_wrap(~year) +
  ggplot2::theme_classic()
```



